export const documents = [
  {
    id: 1,
    name: "Setup Your Company",
  },
];

export const formSteps = [
  {
    id: 1,
    docId: 1,
    stepType: "single",
    label: "Company Details",
  },
  {
    id: 2,
    docId: 1,
    stepType: "multiple",
    label: "Shareholder Details",
  },
  {
    id: 3,
    docId: 1,
    stepType: "single",
    label: "Upload Documents",
  },
];

export const stepsHeaders = [
  {
    id: 1,
    stepId: 1,
    docId: 1,
    heading: "Enter Company Details",
    subHeading: [
      "Please add minimum 1 shareholder details to proceed. You can also invite shareholders to input their details and upload documents",
    ],
  },
  {
    id: 1,
    stepId: 2,
    docId: 1,
    heading: "Enter Shareholder Details",
    subHeading: [
      "Please add minimum 1 shareholder details to proceed. You can also invite shareholders to input their details and upload documents",
    ],
  },
  {
    id: 1,
    stepId: 3,
    docId: 1,
    heading: "Upload Documents",
    subHeading: [
      "Securely submit required documents by uploading them here.  Please ensure all necessary files are attached",
    ],
  },
];

export const stepperFields = [
  {
    id: 1,
    stepId: 1,
    docId: 1,
    label: "COMPANY NAME OPTIONS",
  },
  {
    id: 2,
    stepId: 1,
    docId: 1,
    label: "LICENSE TYPE",
  },
  {
    id: 3,
    stepId: 1,
    docId: 1,
    label: "ACTIVITY DETAILS",
  },
  {
    id: 4,
    stepId: 1,
    docId: 1,
    label: "SHARE CAPITAL DETAILS",
  },
  {
    id: 5,
    stepId: 2,
    docId: 1,
    label: "PERSONAL DETAILS",
  },
  {
    id: 6,
    stepId: 2,
    docId: 1,
    label: "PASSPORT DETAILS",
  },
  {
    id: 7,
    stepId: 3,
    docId: 1,
    label: "Passport",
  },
  {
    id: 8,
    stepId: 3,
    docId: 1,
    label: "Emirates ID card",
  },
];

export const stepInputFields = [
  {
    id: 1,
    fieldId: 1,
    label: "Name option 1",
    placeholder: "Company Name Option 1",
    type: "text",
    name: "nameOption1",
    required: true,
  },
  {
    id: 2,
    fieldId: 1,
    label: "Name option 2",
    placeholder: "Company Name Option 2",
    type: "text",
    name: "nameOption2",
    required: true,
  },
  {
    id: 3,
    fieldId: 1,
    label: "Name option 3",
    placeholder: "Company Name Option 3",
    type: "text",
    name: "nameOption3",
    required: true,
  },
  {
    id: 4,
    fieldId: 2,
    label: "License Type",
    placeholder: "Select license",
    type: "select",
    name: "licenseType",
    valueOptions: ["License1", "License2", "License3", "License4", "License5"],
    required: true,
  },
  {
    id: 5,
    fieldId: 3,
    label: "Activity Details",
    placeholder: "Select Activity",
    type: "select",
    name: "activityDetails",
    valueOptions: ["Activity1", "Activity2", "Activity3", "Activity4"],
    required: true,
  },
  {
    id: 6,
    fieldId: 4,
    label: "Number of shareholders",
    placeholder: "Enter total shareholders",
    type: "number",
    name: "numberOfShareholders",
    required: true,
  },
  {
    id: 7,
    fieldId: 4,
    label: "Proposed share capital",
    placeholder: "Enter share capital",
    type: "number",
    name: "proposedShareCapital",
    required: true,
  },
  {
    id: 8,
    fieldId: 4,
    label: "Share value",
    placeholder: "Enter share value",
    type: "number",
    name: "shareValue",
    required: true,
  },
  {
    id: 9,
    fieldId: 4,
    label: "Share capital per shareholder",
    placeholder: "Enter share capital per owner",
    type: "number",
    name: "shareCapitalPerShareholder",
    required: true,
  },
  {
    id: 10,
    fieldId: 5,
    label: "Title",
    type: "radio",
    name: "title",
    valueOptions: ["Mr.", "Mrs.", "Miss."],
    required: true,
  },
  {
    id: 11,
    fieldId: 5,
    label: "First name",
    placeholder: "First name",
    type: "text",
    name: "firstName",
    required: true,
  },
  {
    id: 12,
    fieldId: 5,
    label: "Middle Name",
    placeholder: "Middle name",
    type: "text",
    name: "middleName",
    required: true,
  },
  {
    id: 12,
    fieldId: 5,
    label: "Last Name",
    placeholder: "Last name",
    type: "text",
    name: "lastName",
    required: true,
  },
  {
    id: 13,
    fieldId: 5,
    label: "Email",
    placeholder: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 14,
    fieldId: 5,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },
  {
    id: 15,
    fieldId: 5,
    label: "Number of shares",
    placeholder: "Number of shares",
    type: "text",
    name: "numberOfShares",
    required: true,
  },
  {
    id: 16,
    fieldId: 5,
    label: "Gender",
    type: "radio",
    name: "gender",
    valueOptions: ["Male", "Female"],
    required: true,
  },
  {
    id: 17,
    fieldId: 5,
    label: "Date of Birth",
    type: "date",
    name: "dob",
    placeholder: "2000/05/31",
    required: true,
  },
  {
    id: 18,
    fieldId: 6,
    label: "Passport number",
    type: "text",
    name: "passportNumber",
    placeholder: "Passport number",
    required: true,
  },
  {
    id: 19,
    fieldId: 6,
    label: "Select country of issue",
    type: "select",
    name: "countryOfIssue",
    placeholder: "Select Country",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
  },
  {
    id: 20,
    fieldId: 6,
    label: "Passport issue date",
    type: "date",
    name: "passportIssueDate",
    placeholder: "2000/05/31",
    required: true,
  },
  {
    id: 21,
    fieldId: 6,
    label: "Passport expiry date",
    type: "date",
    name: "passportExpiryDate",
    placeholder: "2000/05/31",
    required: true,
  },
  {
    id: 22,
    fieldId: 7,
    label: "Upload Passport",
    type: "file",
    name: "passport",
    required: true,
  },
  {
    id: 23,
    fieldId: 8,
    label: "Are you a legal resident of the UAE?",
    type: "radio",
    valueOptions: ["Yes.", "No."],
    name: "isLegalResident",
    required: true,
  },
  {
    id: 24,
    fieldId: 8,
    label: "Upload  Emirates ID card",
    type: "file",
    name: "emiratesId",
    required: true,
  },
];

export const stepFields = [
  {
    id: 1,
    stepId: 1,
    label: "Full Name",
    placeholder: "Full Name",
    type: "text",
    name: "fullName",
    required: true,
  },
  {
    id: 2,
    stepId: 1,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 3,
    stepId: 1,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },
  {
    id: 4,
    stepId: 2,
    label: "Executors Full Name",
    placeholder: "Full Name",
    type: "text",
    name: "fullName",
    required: true,
  },
  {
    id: 5,
    stepId: 2,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 6,
    stepId: 2,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },
  {
    id: 7,
    stepId: 3,
    label: "Beneficiaries Full Name",
    placeholder: "Full Name",
    type: "text",
    name: "fullName",
    required: true,
  },
  {
    id: 8,
    stepId: 3,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 9,
    stepId: 3,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },

  {
    id: 10,
    stepId: 4,
    label: "Asset Allocatio Name",
    placeholder: "Asset Allocatio",
    type: "text",
    name: "assetAllocatio",
    required: true,
  },
  {
    id: 11,
    stepId: 4,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 12,
    stepId: 4,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },
];
