export const documents = [
  {
    id: 1,
    name: "Setup Your Company",
  },
  {
    id: 2,
    name: "Legal Draft Will",
  },
];

export const formSteps = [
  {
    id: 1,
    docId: 1,
    stepType: "single",
    label: "Company Details",
  },
  {
    id: 2,
    docId: 1,
    stepType: "multiple",
    label: "Shareholder Details",
  },
  {
    id: 3,
    docId: 1,
    stepType: "single",
    label: "Upload Documents",
  },
  {
    id: 4,
    docId: 2,
    stepType: "single",
    label: "Personal Details",
  },
  {
    id: 5,
    docId: 2,
    stepType: "single",
    label: "Executors",
  },
  {
    id: 6,
    docId: 2,
    stepType: "single",
    label: "Beneficiaries",
  },
];

export const stepsHeaders = [
  {
    id: 1,
    stepId: 1,
    docId: 1,
    heading: "Enter Company Details",
    subHeading: [
      "Please add minimum 1 shareholder details to proceed. You can also invite shareholders to input their details and upload documents",
    ],
  },
  {
    id: 2,
    stepId: 2,
    docId: 1,
    heading: "Enter Shareholder Details",
    subHeading: [
      "Please add minimum 1 shareholder details to proceed. You can also invite shareholders to input their details and upload documents",
    ],
  },
  {
    id: 3,
    stepId: 3,
    docId: 1,
    heading: "Upload Documents",
    subHeading: [
      "Securely submit required documents by uploading them here.  Please ensure all necessary files are attached",
    ],
  },
  {
    id: 4,
    stepId: 4,
    docId: 2,
    heading: "First, we need some details from you",
    subHeading: [],
  },
  {
    id: 5,
    stepId: 5,
    docId: 2,
    heading: "Who will be the Executor(s) of your Will?",
    subHeading: [
      "The Main Executor is the person appointed to carry out the wishes of this Will.",
      "An Executor must be over the age of 21, not be a bankrupt and is of sound mind to carry out his or her duties under the Will upon the Testator’s demise. An Executor can also be a Beneficiary under a Will",
    ],
  },
  {
    id: 6,
    stepId: 6,
    docId: 2,
    heading: "Who will be the Beneficiaries of Your Will?",
    subHeading: [
      "The Beneficiaries are the people who will benefit from the asset allocation indicated in this will.",
    ],
  },
];

export const stepperFields = [
  {
    id: 1,
    stepId: 1,
    docId: 1,
    label: "COMPANY NAME OPTIONS",
  },
  {
    id: 2,
    stepId: 1,
    docId: 1,
    label: "LICENSE TYPE",
  },
  {
    id: 3,
    stepId: 1,
    docId: 1,
    label: "ACTIVITY DETAILS",
  },
  {
    id: 4,
    stepId: 1,
    docId: 1,
    label: "SHARE CAPITAL DETAILS",
  },
  {
    id: 5,
    stepId: 2,
    docId: 1,
    label: "PERSONAL DETAILS",
  },
  {
    id: 6,
    stepId: 2,
    docId: 1,
    label: "PASSPORT DETAILS",
  },
  {
    id: 7,
    stepId: 3,
    docId: 1,
    label: "Passport",
  },
  {
    id: 8,
    stepId: 3,
    docId: 1,
    label: "Emirates ID card",
  },
  {
    id: 9,
    stepId: 4,
    docId: 2,
    label: "",
  },
  {
    id: 10,
    stepId: 4,
    docId: 2,
    label: "Address",
  },
  {
    id: 11,
    stepId: 5,
    docId: 2,
    label: "",
  },
  {
    id: 12,
    stepId: 5,
    docId: 2,
    label: "Address",
  },
  {
    id: 13,
    stepId: 6,
    docId: 2,
    label: "",
  },
  {
    id: 14,
    stepId: 6,
    docId: 2,
    label: "Address",
  },
];

export const stepInputFields = [
  {
    id: 1,
    fieldId: 1,
    label: "Name option 1",
    placeholder: "Company Name Option 1",
    type: "text",
    width: 4,
    name: "nameOption1",
    required: true,
  },
  {
    id: 2,
    fieldId: 1,
    label: "Name option 2",
    placeholder: "Company Name Option 2",
    type: "text",
    name: "nameOption2",
    required: true,
    width: 4,
  },
  {
    id: 3,
    fieldId: 1,
    label: "Name option 3",
    placeholder: "Company Name Option 3",
    type: "text",
    name: "nameOption3",
    required: true,
    width: 4,
  },
  {
    id: 4,
    fieldId: 2,
    label: "License Type",
    placeholder: "Select license",
    type: "select",
    name: "licenseType",
    valueOptions: ["License1", "License2", "License3", "License4", "License5"],
    required: true,
    width: 4,
  },
  {
    id: 5,
    fieldId: 3,
    label: "Activity Details",
    placeholder: "Select Activity",
    type: "select",
    name: "activityDetails",
    valueOptions: ["Activity1", "Activity2", "Activity3", "Activity4"],
    required: true,
    width: 4,
  },
  {
    id: 6,
    fieldId: 4,
    label: "Number of shareholders",
    placeholder: "Enter total shareholders",
    type: "number",
    name: "numberOfShareholders",
    required: true,
    width: 4,
  },
  {
    id: 7,
    fieldId: 4,
    label: "Proposed share capital",
    placeholder: "Enter share capital",
    type: "number",
    name: "proposedShareCapital",
    required: true,
    width: 4,
  },
  {
    id: 8,
    fieldId: 4,
    label: "Share value",
    placeholder: "Enter share value",
    type: "number",
    name: "shareValue",
    required: true,
    width: 4,
  },
  {
    id: 9,
    fieldId: 4,
    label: "Share capital per shareholder",
    placeholder: "Enter share capital per owner",
    type: "number",
    name: "shareCapitalPerShareholder",
    required: true,
    width: 4,
  },
  {
    id: 10,
    fieldId: 5,
    label: "Title",
    type: "radio",
    name: "title",
    valueOptions: ["Mr.", "Mrs.", "Miss."],
    required: true,
    width: 12,
  },
  {
    id: 11,
    fieldId: 5,
    label: "First name",
    placeholder: "First name",
    type: "text",
    name: "firstName",
    required: true,
    width: 4,
  },
  {
    id: 12,
    fieldId: 5,
    label: "Middle Name",
    placeholder: "Middle name",
    type: "text",
    name: "middleName",
    required: true,
    width: 4,
  },
  {
    id: 12,
    fieldId: 5,
    label: "Last Name",
    placeholder: "Last name",
    type: "text",
    name: "lastName",
    required: true,
    width: 4,
  },
  {
    id: 13,
    fieldId: 5,
    label: "Email",
    placeholder: "Email",
    type: "email",
    name: "email",
    required: true,
    width: 4,
  },
  {
    id: 14,
    fieldId: 5,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
    width: 4,
  },
  {
    id: 15,
    fieldId: 5,
    label: "Number of shares",
    placeholder: "Number of shares",
    type: "text",
    name: "numberOfShares",
    required: true,
    width: 4,
  },
  {
    id: 16,
    fieldId: 5,
    label: "Gender",
    type: "radio",
    name: "gender",
    valueOptions: ["Male", "Female"],
    required: true,
    width: 4,
  },
  {
    id: 17,
    fieldId: 5,
    label: "Date of Birth",
    type: "date",
    name: "dob",
    placeholder: "2000/05/31",
    required: true,
    width: 4,
  },
  {
    id: 18,
    fieldId: 6,
    label: "Passport number",
    type: "text",
    name: "passportNumber",
    placeholder: "Passport number",
    required: true,
    width: 4,
  },
  {
    id: 19,
    fieldId: 6,
    label: "Select country of issue",
    type: "select",
    name: "countryOfIssue",
    placeholder: "Select Country",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
    width: 8,
  },
  {
    id: 20,
    fieldId: 6,
    label: "Passport issue date",
    type: "date",
    name: "passportIssueDate",
    placeholder: "2000/05/31",
    required: true,
    width: 4,
  },
  {
    id: 21,
    fieldId: 6,
    label: "Passport expiry date",
    type: "date",
    name: "passportExpiryDate",
    placeholder: "2000/05/31",
    required: true,
    width: 4,
  },
  {
    id: 22,
    fieldId: 7,
    label: "Upload Passport",
    type: "file",
    name: "passport",
    required: true,
    width: 12,
  },
  {
    id: 23,
    fieldId: 8,
    label: "Are you a legal resident of the UAE?",
    type: "radio",
    valueOptions: ["Yes.", "No."],
    name: "isLegalResident",
    required: true,
    width: 4,
  },
  {
    id: 24,
    fieldId: 8,
    label: "Upload  Emirates ID card",
    type: "file",
    name: "emiratesId",
    required: true,
    width: 12,
  },

  {
    id: 25,
    fieldId: 9,
    label: "Full Name",
    type: "text",
    placeholder: "Enter Full Name",
    name: "fullName",
    required: true,
    width: 6,
  },

  {
    id: 28,
    fieldId: 9,
    label: "Gender",
    type: "radio",
    name: "gender",
    valueOptions: ["Male", "Female", "Other"],
    required: true,
    width: 6,
  },
  {
    id: 29,
    fieldId: 9,
    label: "Date of Birth",
    type: "date",
    name: "dob",
    required: true,
    width: 6,
  },
  {
    id: 30,
    fieldId: 9,
    label: "Citizenship",
    type: "select",
    name: "citizenship",
    placeholder: "Citizenship",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
    width: 6,
  },
  {
    id: 31,
    fieldId: 9,
    label: "Type of ID",
    type: "select",
    name: "idType",
    placeholder: "Type of ID",
    valueOptions: ["Passport", "Drivers License", "National ID"],
    required: true,
    width: 6,
  },
  {
    id: 32,
    fieldId: 9,
    label: "NID/Passport/Bitrh Certificate",
    type: "text",
    name: "idNumber",
    placeholder: "eg. 123456789",
    required: true,
    width: 6,
  },
  {
    id: 33,
    fieldId: 10,
    label: "Address Line 1",
    type: "text",
    name: "addressLine1",
    placeholder: "line 1",
    required: true,
    width: 12,
  },
  {
    id: 34,
    fieldId: 10,
    label: "Address Line 2",
    type: "text",
    name: "addressLine2",
    placeholder: "line 2",
    required: true,
    width: 12,
  },
  {
    id: 35,
    fieldId: 10,
    label: "Country",
    type: "select",
    name: "country",
    placeholder: "Select Country",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
    width: 3,
  },
  {
    id: 36,
    fieldId: 10,
    label: "Postal Code",
    type: "text",
    name: "postalCode",
    placeholder: "eg. 5403",
    required: true,
    width: 3,
  },
  {
    id: 37,
    fieldId: 11,
    label: "Full Name of Main Executors",
    type: "text",
    name: "fullName",
    placeholder: "Full Name",
    required: true,
    width: 12,
  },
  {
    id: 38,
    fieldId: 11,
    label: "Type of ID",
    type: "select",
    name: "idType",
    placeholder: "Type of ID",
    valueOptions: ["Passport", "Drivers License", "National ID"],
    required: true,
    width: 6,
  },
  {
    id: 39,
    fieldId: 11,
    label: "NID/Passport/Bitrh Certificate",
    type: "text",
    name: "idNumber",
    placeholder: "eg. 123456789",
    required: true,
    width: 6,
  },
  {
    id: 40,
    fieldId: 11,
    label: "Citizenship",
    type: "select",
    name: "citizenship",
    placeholder: "Citizenship",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
    width: 6,
  },
  {
    id: 41,
    fieldId: 12,
    label: "Address Line 1",
    type: "text",
    name: "addressLine1",
    placeholder: "line 1",
    required: true,
    width: 12,
  },
  {
    id: 42,
    fieldId: 12,
    label: "Address Line 2",
    type: "text",
    name: "addressLine2",
    placeholder: "line 2",
    required: true,
    width: 12,
  },
  {
    id: 43,
    fieldId: 12,
    label: "Country",
    type: "select",
    name: "country",
    placeholder: "Select Country",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
    width: 3,
  },
  {
    id: 44,
    fieldId: 12,
    label: "Postal Code",
    type: "text",
    name: "postalCode",
    placeholder: "eg. 5403",
    required: true,
    width: 3,
  },
  {
    id: 45,
    fieldId: 13,
    label: "Full Name of Beneficiaries",
    type: "text",
    name: "fullName",
    placeholder: "Full Name",
    required: true,
    width: 12,
  },
  {
    id: 46,
    fieldId: 13,
    label: "Type of ID",
    type: "select",
    name: "idType",
    placeholder: "Type of ID",
    valueOptions: ["Passport", "Drivers License", "National ID"],
    required: true,
    width: 6,
  },
  {
    id: 47,
    fieldId: 13,
    label: "NID/Passport/Bitrh Certificate",
    type: "text",
    name: "idNumber",
    placeholder: "eg. 123456789",
    required: true,
    width: 6,
  },
  {
    id: 48,
    fieldId: 13,
    label: "Citizenship",
    type: "select",
    name: "citizenship",
    placeholder: "Citizenship",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
    width: 6,
  },
  {
    id: 49,
    fieldId: 14,
    label: "Address Line 1",
    type: "text",
    name: "addressLine1",
    placeholder: "line 1",
    required: true,
    width: 12,
  },
  {
    id: 50,
    fieldId: 14,
    label: "Address Line 2",
    type: "text",
    name: "addressLine2",
    placeholder: "line 2",
    required: true,
    width: 12,
  },
  {
    id: 51,
    fieldId: 14,
    label: "Country",
    type: "select",
    name: "country",
    placeholder: "Select Country",
    valueOptions: ["Nigeria", "Ghana", "Togo", "Cameroon"],
    required: true,
    width: 3,
  },
  {
    id: 51,
    fieldId: 14,
    label: "Postal Code",
    type: "text",
    name: "postalCode",
    placeholder: "eg. 5403",
    required: true,
    width: 3,
  },
];

export const stepFields = [
  {
    id: 1,
    stepId: 1,
    label: "Full Name",
    placeholder: "Full Name",
    type: "text",
    name: "fullName",
    required: true,
  },
  {
    id: 2,
    stepId: 1,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 3,
    stepId: 1,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },
  {
    id: 4,
    stepId: 2,
    label: "Executors Full Name",
    placeholder: "Full Name",
    type: "text",
    name: "fullName",
    required: true,
  },
  {
    id: 5,
    stepId: 2,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 6,
    stepId: 2,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },
  {
    id: 7,
    stepId: 3,
    label: "Beneficiaries Full Name",
    placeholder: "Full Name",
    type: "text",
    name: "fullName",
    required: true,
  },
  {
    id: 8,
    stepId: 3,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 9,
    stepId: 3,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },

  {
    id: 10,
    stepId: 4,
    label: "Asset Allocatio Name",
    placeholder: "Asset Allocatio",
    type: "text",
    name: "assetAllocatio",
    required: true,
  },
  {
    id: 11,
    stepId: 4,
    placeholder: "Email",
    label: "Email",
    type: "email",
    name: "email",
    required: true,
  },
  {
    id: 12,
    stepId: 4,
    label: "Phone",
    placeholder: "Phone",
    type: "text",
    name: "phone",
    required: true,
  },
];
